In [1]:
import numpy as np
import pandas as pd

In [2]:
books = pd.read_csv("Books.csv")
users = pd.read_csv("Users.csv")
rating = pd.read_csv("Ratings.csv")

C:\Users\Asus\AppData\Local\Temp\ipykernel_13680\3870624997.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("Books.csv")

In [3]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [5]:
rating.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [6]:
print(books.shape)
print(rating.shape)
print(users.shape)

(271360, 8)
(1149780, 3)
(278858, 3)

In [7]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [8]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [9]:
rating.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [10]:
books.duplicated().sum()

0

In [11]:
rating.duplicated().sum()

0

In [12]:
users.duplicated().sum()

0

In [13]:
### Build a popularity based model(KNN)

In [14]:
1. we display the top 50 books with highest rating with consider only those books which has got minimum 250 books

SyntaxError: invalid syntax (514654238.py, line 1)

In [15]:
# merge books and rating column on isbn
new_df = rating.merge(books,on="ISBN")

In [16]:
new_df.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...

In [17]:
num_df = new_df.groupby("Book-Title").count()["Book-Rating"].reset_index()
num_df.head()

                                          Book-Title  Book-Rating
0   A Light in the Storm: The Civil War Diary of ...            4
1                              Always Have Popsicles            1
2               Apple Magic (The Collector's series)            1
3   Ask Lily (Young Women of Faith: Lily Series, ...            1
4   Beyond IBM: Leadership Marketing and Finance ...            1

In [18]:
num_df.rename(columns = {"Book-Rating":"num-rating"},inplace=True)
num_df.head()

                                          Book-Title  num-rating
0   A Light in the Storm: The Civil War Diary of ...           4
1                              Always Have Popsicles           1
2               Apple Magic (The Collector's series)           1
3   Ask Lily (Young Women of Faith: Lily Series, ...           1
4   Beyond IBM: Leadership Marketing and Finance ...           1

In [19]:
avg_rating = new_df.groupby("Book-Title")["Book-Rating"].mean().reset_index()
avg_rating.head()

                                          Book-Title  Book-Rating
0   A Light in the Storm: The Civil War Diary of ...         2.25
1                              Always Have Popsicles         0.00
2               Apple Magic (The Collector's series)         0.00
3   Ask Lily (Young Women of Faith: Lily Series, ...         8.00
4   Beyond IBM: Leadership Marketing and Finance ...         0.00

In [20]:
avg_rating.rename(columns = {"Book-Rating":"Average-Rating"},inplace = True)
avg_rating

                                               Book-Title  Average-Rating
0        A Light in the Storm: The Civil War Diary of ...        2.250000
1                                   Always Have Popsicles        0.000000
2                    Apple Magic (The Collector's series)        0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...        8.000000
4        Beyond IBM: Leadership Marketing and Finance ...        0.000000
...                                                   ...             ...
241066                                      Ã?Â?lpiraten.        0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.        5.250000
241068                                Ã?Â?sterlich leben.        7.000000
241069                              Ã?Â?stlich der Berge.        2.666667
241070                                  Ã?Â?thique en toc        4.000000

[241071 rows x 2 columns]

In [21]:
# now merge both the dataframe 
populer_df = avg_rating.merge(num_df,on="Book-Title")
populer_df.head()

,Book-Title,Average-Rating,num-rating
0,A Light in the Storm: The Civil War Diary of ...,2.25,4
1,Always Have Popsicles,0.00,1
2,Apple Magic (The Collector's series),0.00,1
3,"Ask Lily (Young Women of Faith: Lily Series, ...",8.00,1
4,Beyond IBM: Leadership Marketing and Finance ...,0.00,1

In [22]:
# now filter top 50 movie with highest rating and more then 250 rating
populer_df = populer_df[populer_df["num-rating"]>=250].sort_values("Average-Rating",ascending=False)
populer_df.head()

,Book-Title,Average-Rating,num-rating
80434,Harry Potter and the Prisoner of Azkaban (Book 3),5.852804,428
80422,Harry Potter and the Goblet of Fire (Book 4),5.824289,387
80441,Harry Potter and the Sorcerer's Stone (Book 1),5.737410,278
80426,Harry Potter and the Order of the Phoenix (Boo...,5.501441,347
80414,Harry Potter and the Chamber of Secrets (Book 2),5.183453,556

In [23]:
top_50 = populer_df.head(50)
top_50

,Book-Title,Average-Rating,num-rating
80434,Harry Potter and the Prisoner of Azkaban (Book 3),5.852804,428
80422,Harry Potter and the Goblet of Fire (Book 4),5.824289,387
80441,Harry Potter and the Sorcerer's Stone (Book 1),5.737410,278
80426,Harry Potter and the Order of the Phoenix (Boo...,5.501441,347
80414,Harry Potter and the Chamber of Secrets (Book 2),5.183453,556
191612,The Hobbit : The Enchanting Prelude to The Lor...,5.007117,281
187377,The Fellowship of the Ring (The Lord of the Ri...,4.948370,368
80445,Harry Potter and the Sorcerer's Stone (Harry P...,4.895652,575
211384,"The Two Towers (The Lord of the Rings, Part 2)",4.880769,260
219741,To Kill a Mockingbird,4.700000,510
183573,The Da Vinci Code,4.642539,898
187880,The Five People You Meet in Heaven,4.551163,430
180556,The Catcher in the Rye,4.545657,449
196326,The Lovely Bones: A Novel,4.468726,1295
764,1984,4.454225,284
144165,Prodigal Summer: A Novel,4.450593,253
128670,Neverwhere,4.449057,265
206502,The Secret Life of Bees,4.447028,774
168719,Stupid White Men ...and Other Sorry Excuses fo...,4.356890,283
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",4.354970,493
204387,The Red Tent (Bestselling Backlist),4.334716,723
191589,The Hitchhiker's Guide to the Galaxy,4.328358,268
129379,Nickel and Dimed: On (Not) Getting By in America,4.289552,335
93381,Into the Wild,4.273810,252
63867,Fahrenheit 451,4.264059,409
74750,Girl with a Pearl Earring,4.218631,526
136145,Outlander,4.173145,283
233370,Where the Heart Is (Oprah's Book Club (Paperba...,4.105983,585
156102,Seabiscuit: An American Legend,4.098182,275
107962,Life of Pi,4.088855,664
176845,The Bean Trees,4.087404,389
2281,"A Child Called \It\"": One Child's Courage to S...",4.086792,265
8434,ANGELA'S ASHES,4.075269,279
76343,Good in Bed,4.055102,490
64931,Fast Food Nation: The Dark Side of the All-Ame...,4.037383,321
12700,American Gods,4.006623,302
161645,Skipping Christmas,4.006211,322
105777,Left Behind: A Novel of the Earth's Last Days ...,4.003145,318
189551,"The Golden Compass (His Dark Materials, Book 1)",4.000000,336
181679,The Color Purple,3.964968,314
160336,Silence of the Lambs,3.960938,256
8752,About a Boy,3.900763,262
158138,Seven Up (A Stephanie Plum Novel),3.888489,278
175097,The Alchemist: A Fable About Following Your Dream,3.875940,266
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,3.825279,269
170101,Suzanne's Diary for Nicholas,3.820569,457
111073,Lord of the Flies,3.818533,259
5664,A Prayer for Owen Meany,3.796610,413
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",3.777409,301
233851,White Oleander : A Novel (Oprah's Book Club),3.772472,356

In [24]:
# top_50.merge(books,on="Book_Title") #.drop_duplicate("Book-Title")
top_50 = top_50.merge(books,on="Book-Title")
top_50.shape

(196, 10)

In [25]:
top_50 = top_50.drop_duplicates("Book-Title")
top_50.shape

(50, 10)

In [26]:
top_50.head()

,Book-Title,Average-Rating,num-rating,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,Harry Potter and the Prisoner of Azkaban (Book 3),5.852804,428,0439136350,J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...
3,Harry Potter and the Goblet of Fire (Book 4),5.824289,387,0439139597,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...
5,Harry Potter and the Sorcerer's Stone (Book 1),5.737410,278,0590353403,J. K. Rowling,1998,Scholastic,http://images.amazon.com/images/P/0590353403.0...,http://images.amazon.com/images/P/0590353403.0...,http://images.amazon.com/images/P/0590353403.0...
9,Harry Potter and the Order of the Phoenix (Boo...,5.501441,347,043935806X,J. K. Rowling,2003,Scholastic,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...
13,Harry Potter and the Chamber of Secrets (Book 2),5.183453,556,0439064872,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...

In [29]:
# now filter columns 
populer_50 = top_50[["Book-Title","Average-Rating","num-rating","Book-Author","Image-URL-M"]]

In [30]:
populer_50

,Book-Title,Average-Rating,num-rating,Book-Author,Image-URL-M
0,Harry Potter and the Prisoner of Azkaban (Book 3),5.852804,428,J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...
3,Harry Potter and the Goblet of Fire (Book 4),5.824289,387,J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...
5,Harry Potter and the Sorcerer's Stone (Book 1),5.737410,278,J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...
9,Harry Potter and the Order of the Phoenix (Boo...,5.501441,347,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...
13,Harry Potter and the Chamber of Secrets (Book 2),5.183453,556,J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...
16,The Hobbit : The Enchanting Prelude to The Lor...,5.007117,281,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...
17,The Fellowship of the Ring (The Lord of the Ri...,4.948370,368,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...
26,Harry Potter and the Sorcerer's Stone (Harry P...,4.895652,575,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...
28,"The Two Towers (The Lord of the Rings, Part 2)",4.880769,260,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...
39,To Kill a Mockingbird,4.700000,510,Harper Lee,http://images.amazon.com/images/P/0446310786.0...
47,The Da Vinci Code,4.642539,898,Dan Brown,http://images.amazon.com/images/P/0385504209.0...
53,The Five People You Meet in Heaven,4.551163,430,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...
55,The Catcher in the Rye,4.545657,449,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...
62,The Lovely Bones: A Novel,4.468726,1295,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...
63,1984,4.454225,284,George Orwell,http://images.amazon.com/images/P/0451524934.0...
72,Prodigal Summer: A Novel,4.450593,253,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...
73,Neverwhere,4.449057,265,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...
78,The Secret Life of Bees,4.447028,774,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...
84,Stupid White Men ...and Other Sorry Excuses fo...,4.356890,283,Michael Moore,http://images.amazon.com/images/P/0060392452.0...
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",4.354970,493,MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...
88,The Red Tent (Bestselling Backlist),4.334716,723,Anita Diamant,http://images.amazon.com/images/P/0312195516.0...
89,The Hitchhiker's Guide to the Galaxy,4.328358,268,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...
98,Nickel and Dimed: On (Not) Getting By in America,4.289552,335,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...
100,Into the Wild,4.273810,252,Jon Krakauer,http://images.amazon.com/images/P/0385486804.0...
103,Fahrenheit 451,4.264059,409,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...
116,Girl with a Pearl Earring,4.218631,526,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...
117,Outlander,4.173145,283,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...
123,Where the Heart Is (Oprah's Book Club (Paperba...,4.105983,585,Billie Letts,http://images.amazon.com/images/P/0446672211.0...
124,Seabiscuit: An American Legend,4.098182,275,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...
126,Life of Pi,4.088855,664,Yann Martel,http://images.amazon.com/images/P/0151008116.0...
130,The Bean Trees,4.087404,389,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...
133,"A Child Called \It\"": One Child's Courage to S...",4.086792,265,Dave Pelzer,http://images.amazon.com/images/P/1558743669.0...
135,ANGELA'S ASHES,4.075269,279,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...
137,Good in Bed,4.055102,490,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...
139,Fast Food Nation: The Dark Side of the All-Ame...,4.037383,321,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...
140,American Gods,4.006623,302,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...
141,Skipping Christmas,4.006211,322,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...
147,Left Behind: A Novel of the Earth's Last Days ...,4.003145,318,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...
149,"The Golden Compass (His Dark Materials, Book 1)",4.000000,336,PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...
157,The Color Purple,3.964968,314,Alice Walker,http://images.amazon.com/images/P/0671617028.0...
163,Silence of the Lambs,3.960938,256,Thomas Harris,http://images.amazon.com/images/P/0312924585.0...
166,About a Boy,3.900763,262,Nick Hornby,http://images.amazon.com/images/P/1573227331.0...
173,Seven Up (A Stephanie Plum Novel),3.888489,278,Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...
175,The Alchemist: A Fable About Following Your Dream,3.875940,266,Paulo Coelho,http://images.amazon.com/images/P/0062502174.0...
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,3.825279,269,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...
182,Suzanne's Diary for Nicholas,3.820569,457,James Patterson,http://images.amazon.com/images/P/0316969443.0...
186,Lord of the Flies,3.818533,259,William Gerald Golding,http://images.amazon.com/images/P/0399501487.0...
192,A Prayer for Owen Meany,3.796610,413,John Irving,http://images.amazon.com/images/P/0345361792.0...
194,"The Vampire Lestat (Vampire Chronicles, Book II)",3.777409,301,ANNE RICE,http://images.amazon.com/images/P/0345313860.0...
195,White Oleander : A Novel (Oprah's Book Club),3.772472,356,Janet Fitch,http://images.amazon.com/images/P/0316284955.0...

### colaborating filtering based recommander system

In [ ]:
# filter those user which is rate more then 200 books the chooice those book which is more then ratings

In [31]:
x = new_df.groupby("User-ID").count()["Book-Rating"]>200

In [32]:
x_ind = x[x].index

In [33]:
x_ind

Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,   6323,
         6543,
       ...
       271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427, 277639,
       278418],
      dtype='int64', name='User-ID', length=811)

In [34]:
x_ind.shape

(811,)

In [35]:
filtered_rating = new_df[new_df["User-ID"].isin(x_ind)]
filtered_rating.shape

(474007, 10)

In [36]:
# now filtered on the bases on books
y = filtered_rating.groupby("Book-Title").count()["Book-Rating"]>50
y

Book-Title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    False
 Always Have Popsicles                                                                                        False
 Apple Magic (The Collector's series)                                                                         False
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   False
 Clifford Visita El Hospital (Clifford El Gran Perro Colorado)                                                False
                                                                                                              ...
Ã?Â?ber das Fernsehen.                                                                                        False
Ã?Â?ber die Pflicht zum Ungehorsam gegen den Staat.                                                           False
Ã?Â?lpiraten.                                                                                                 False
Ã?Â?stlich der Berge.                                                                                         False
Ã?Â?thique en toc                                                                                             False
Name: Book-Rating, Length: 155845, dtype: bool

In [37]:
famous_book = y[y].index

In [38]:
final_rating = filtered_rating[filtered_rating["Book-Title"].isin(famous_book)]
final_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1163,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...
1165,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...
1168,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...,http://images.amazon.com/images/P/0061009059.0...,http://images.amazon.com/images/P/0061009059.0...
1174,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...,http://images.amazon.com/images/P/006440188X.0...,http://images.amazon.com/images/P/006440188X.0...
...,...,...,...,...,...,...,...,...,...,...
1029196,275970,1400031354,0,Tears of the Giraffe (No.1 Ladies Detective Ag...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031354.0...,http://images.amazon.com/images/P/1400031354.0...,http://images.amazon.com/images/P/1400031354.0...
1029197,275970,1400031362,0,Morality for Beautiful Girls (No.1 Ladies Dete...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031362.0...,http://images.amazon.com/images/P/1400031362.0...,http://images.amazon.com/images/P/1400031362.0...
1029270,275970,1573229725,0,Fingersmith,Sarah Waters,2002,Riverhead Books,http://images.amazon.com/images/P/1573229725.0...,http://images.amazon.com/images/P/1573229725.0...,http://images.amazon.com/images/P/1573229725.0...
1029309,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...
1029310,275970,1586212230,0,Naked,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586212230.0...,http://images.amazon.com/images/P/1586212230.0...,http://images.amazon.com/images/P/1586212230.0...

In [39]:
# create a pivot table
pt = final_rating.pivot_table(index="Book-Title",columns = "User-ID",values = "Book-Rating")

In [40]:
pt.fillna(0,inplace=True)
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

### Now calculate the distances

In [41]:
 # calculate eucledian distance
from sklearn.metrics.pairwise import cosine_similarity

In [42]:
similarity_score = cosine_similarity(pt)
similarity_score[0]

array([1.        , 0.10255025, 0.01220856, 0.        , 0.05367224,
       0.02774901, 0.08216491, 0.13732869, 0.03261686, 0.03667591,
       0.02322418, 0.06766487, 0.02083978, 0.09673735, 0.08303112,
       0.11153543, 0.05100411, 0.02517784, 0.11706383, 0.        ,
       0.14333793, 0.07847534, 0.06150451, 0.08723968, 0.        ,
       0.07009814, 0.13658681, 0.07600328, 0.12167134, 0.00768046,
       0.01473221, 0.        , 0.07965814, 0.04522617, 0.01556271,
       0.09495938, 0.0182307 , 0.02610465, 0.07984012, 0.11679969,
       0.0569124 , 0.08354155, 0.08471898, 0.08785938, 0.05491435,
       0.0548505 , 0.27026514, 0.09779123, 0.06016046, 0.08958835,
       0.06748675, 0.        , 0.04468098, 0.01920872, 0.        ,
       0.05629067, 0.00557964, 0.07877059, 0.05219479, 0.18908177,
       0.        , 0.01240656, 0.02984572, 0.04279502, 0.12680125,
       0.16566735, 0.        , 0.13357242, 0.06615478, 0.        ,
       0.        , 0.        , 0.10968075, 0.02806606, 0.04521795,
       0.06876131, 0.01331627, 0.10519138, 0.03349457, 0.01363458,
       0.23669374, 0.        , 0.10397941, 0.06167753, 0.11661083,
       0.08331012, 0.00850895, 0.06715433, 0.        , 0.15850821,
       0.0328052 , 0.01068915, 0.02579782, 0.02114859, 0.02687779,
       0.02175821, 0.        , 0.01601663, 0.04768603, 0.05819184,
       0.06510722, 0.        , 0.0476705 , 0.05273165, 0.0281001 ,
       0.06524573, 0.02116345, 0.02097868, 0.07422249, 0.01752778,
       0.03734567, 0.01579666, 0.11039448, 0.16527277, 0.15514319,
       0.06237454, 0.08139489, 0.05655414, 0.07458203, 0.03771888,
       0.0593633 , 0.02955369, 0.03355603, 0.04734093, 0.01006643,
       0.01671982, 0.07258935, 0.        , 0.        , 0.        ,
       0.02428501, 0.03067819, 0.0997498 , 0.        , 0.01690152,
       0.02410862, 0.0281084 , 0.        , 0.        , 0.01812877,
       0.02880827, 0.05995157, 0.02127671, 0.1034119 , 0.02766748,
       0.10684795, 0.09898722, 0.14145186, 0.05007429, 0.09428289,
       0.01411249, 0.07835976, 0.00882242, 0.04515898, 0.        ,
       0.01281412, 0.04003334, 0.07477661, 0.01217906, 0.01887393,
       0.02667484, 0.01432864, 0.14702847, 0.06087282, 0.02578321,
       0.02741876, 0.        , 0.14909595, 0.05606788, 0.        ,
       0.03199916, 0.03643817, 0.        , 0.01962921, 0.22222254,
       0.01515845, 0.09673268, 0.02190023, 0.02013549, 0.05400331,
       0.07262017, 0.01111637, 0.03649872, 0.05994664, 0.        ,
       0.14691167, 0.02086005, 0.10359635, 0.09794375, 0.06609997,
       0.12871083, 0.08992739, 0.01147457, 0.02460165, 0.        ,
       0.18049207, 0.05141892, 0.0477174 , 0.10849696, 0.13278139,
       0.05915288, 0.05372984, 0.034785  , 0.        , 0.09203039,
       0.06388401, 0.04773328, 0.15570975, 0.08420691, 0.12338217,
       0.0878469 , 0.08205945, 0.02433703, 0.00272862, 0.        ,
       0.03671505, 0.15280984, 0.0370943 , 0.07458136, 0.09746697,
       0.05416091, 0.10266993, 0.07574414, 0.06426526, 0.0360174 ,
       0.01559752, 0.02033559, 0.02463593, 0.        , 0.02135369,
       0.0190337 , 0.06806265, 0.02032116, 0.11784706, 0.07839488,
       0.08422558, 0.        , 0.02040796, 0.        , 0.04698246,
       0.08294513, 0.13974514, 0.01234525, 0.13510608, 0.07423489,
       0.11841889, 0.04930091, 0.01621668, 0.02633023, 0.04815972,
       0.01959826, 0.10174253, 0.13257638, 0.        , 0.0551027 ,
       0.0186115 , 0.        , 0.04504598, 0.03482459, 0.16503292,
       0.08466191, 0.06795353, 0.02987653, 0.        , 0.        ,
       0.08781993, 0.07885279, 0.04799058, 0.01467964, 0.02123837,
       0.04549923, 0.08673969, 0.00885998, 0.02880637, 0.02022145,
       0.02414122, 0.12548312, 0.        , 0.02482518, 0.06520606,
       0.        , 0.0606983 , 0.13974105, 0.01978844, 0.01260824,
       0.08608601, 0.04433883, 0.02943085, 0.02242496, 0.06541868,
       0.07866868, 0.14281399, 0.11979305, 0.01858409, 0.13445377,
       0.09790644, 0.        , 0.17415731, 0.07437756, 0.        ,
       0.12389065, 0.01042391, 0.02580849, 0.        , 0.0895139 ,
       0.04005551, 0.19182231, 0.02267512, 0.01730347, 0.03054044,
       0.07008822, 0.10084626, 0.10467615, 0.01683462, 0.12468283,
       0.10266459, 0.03549836, 0.02667484, 0.07652765, 0.08474056,
       0.01831977, 0.02177482, 0.15293362, 0.        , 0.        ,
       0.01063251, 0.02153089, 0.02946443, 0.        , 0.02076783,
       0.01194825, 0.00953675, 0.2067554 , 0.01554292, 0.0390266 ,
       0.06681046, 0.09014973, 0.05914735, 0.06206857, 0.        ,
       0.02005959, 0.07843566, 0.16337845, 0.07161075, 0.        ,
       0.14595258, 0.02939738, 0.04779629, 0.01807238, 0.11362722,
       0.09791273, 0.07999693, 0.08912337, 0.10941777, 0.        ,
       0.02115842, 0.0600393 , 0.01797154, 0.05755408, 0.02166863,
       0.09754449, 0.13107652, 0.        , 0.06829904, 0.09132922,
       0.        , 0.02781406, 0.01533368, 0.06113179, 0.01757286,
       0.0180158 , 0.11789806, 0.06468143, 0.13904191, 0.        ,
       0.06671644, 0.        , 0.        , 0.05762086, 0.02266096,
       0.00844876, 0.02297481, 0.07136276, 0.15305514, 0.06039874,
       0.        , 0.08996912, 0.01545947, 0.10135299, 0.        ,
       0.01676344, 0.        , 0.0502188 , 0.16041182, 0.        ,
       0.13439733, 0.12508514, 0.02329035, 0.0198727 , 0.01105674,
       0.02548034, 0.00896044, 0.08246122, 0.01902896, 0.07025003,
       0.0216367 , 0.12822982, 0.09998772, 0.06355197, 0.02883024,
       0.04335826, 0.0470659 , 0.05223733, 0.08982751, 0.00875634,
       0.09923542, 0.10228551, 0.        , 0.12307492, 0.01758929,
       0.02028125, 0.1033827 , 0.13028171, 0.08988894, 0.09005001,
       0.05332049, 0.08033436, 0.04597795, 0.06139888, 0.02304904,
       0.06523041, 0.01915363, 0.        , 0.04542766, 0.        ,
       0.        , 0.05261954, 0.01317088, 0.        , 0.        ,
       0.0485931 , 0.0734819 , 0.10354481, 0.01718807, 0.09919937,
       0.08091989, 0.00358835, 0.11122765, 0.05143481, 0.0566614 ,
       0.        , 0.06087719, 0.10800615, 0.        , 0.07554686,
       0.        , 0.13644384, 0.04796763, 0.16104067, 0.01759864,
       0.05438295, 0.        , 0.08100801, 0.13090711, 0.00581844,
       0.07150547, 0.05428487, 0.06143184, 0.05161653, 0.1951182 ,
       0.1149488 , 0.06513047, 0.06401961, 0.        , 0.        ,
       0.10853662, 0.11400426, 0.0463925 , 0.01825277, 0.        ,
       0.01195201, 0.21057744, 0.05809707, 0.04349156, 0.02646256,
       0.07276403, 0.05264857, 0.07242165, 0.06790898, 0.01626564,
       0.02431809, 0.02093565, 0.13617057, 0.11784149, 0.08588206,
       0.09284352, 0.11277297, 0.06868983, 0.08200947, 0.13369059,
       0.        , 0.19972625, 0.02286207, 0.0806288 , 0.        ,
       0.05756015, 0.06738056, 0.19656288, 0.06306426, 0.03499381,
       0.06123119, 0.02180168, 0.02317515, 0.06476149, 0.07052241,
       0.08280452, 0.1700872 , 0.07213921, 0.01172201, 0.08541218,
       0.17990898, 0.08007284, 0.01739625, 0.16728777, 0.26396194,
       0.1840891 , 0.05600273, 0.04133586, 0.06911015, 0.14456847,
       0.22626397, 0.19208896, 0.0239334 , 0.20025064, 0.01507653,
       0.05144282, 0.1233368 , 0.1420166 , 0.02472079, 0.08563805,
       0.02363426, 0.12794024, 0.01083153, 0.07352436, 0.03421895,
       0.07194212, 0.02297079, 0.15344079, 0.08856302, 0.        ,
       0.        , 0.01878656, 0.09772942, 0.04404359, 0.15211972,
       0.0152225 , 0.10307399, 0.05715789, 0.04600056, 0.06303899,
       0.06572303, 0.14421331, 0.        , 0.04203701, 0.02276077,
       0.17381829, 0.01909967, 0.16000268, 0.        , 0.05940546,
       0.07725115, 0.07464763, 0.06546696, 0.07021577, 0.18921368,
       0.02494136, 0.01705027, 0.05437622, 0.04932819, 0.        ,
       0.11445399, 0.08001595, 0.12858515, 0.02306658, 0.06129105,
       0.02090769, 0.04550867, 0.1026659 , 0.10725982, 0.0260534 ,
       0.00173709, 0.0987294 , 0.08077482, 0.02159226, 0.01614275,
       0.0208464 , 0.09797466, 0.01906731, 0.18571699, 0.05344577,
       0.18925314, 0.05894189, 0.01488161, 0.1202478 , 0.09840359,
       0.01048126, 0.10596224, 0.07617195, 0.0805439 , 0.        ,
       0.23299389, 0.01073642, 0.13573542, 0.04578552, 0.14440017,
       0.        , 0.12522954, 0.0645501 , 0.02817522, 0.14445559,
       0.01721045, 0.09508161, 0.0517902 , 0.18410818, 0.08704224,
       0.10850377, 0.03954865, 0.0383631 , 0.02463491, 0.07845405,
       0.03455548, 0.03007681, 0.02484076, 0.04223674, 0.14444517,
       0.12340234, 0.01510201, 0.0284437 , 0.02132016, 0.07391778,
       0.08904276, 0.15893871, 0.06947574, 0.01060787, 0.        ,
       0.09993169, 0.05711356, 0.09488374, 0.13365876, 0.05794064,
       0.        , 0.06721284, 0.02066998, 0.        , 0.01839428,
       0.        , 0.12655364, 0.08418288, 0.09095705, 0.00730589,
       0.08143881, 0.        , 0.04218803, 0.08392849, 0.07785801,
       0.07151794, 0.02407593, 0.01635126, 0.03734567, 0.05237227,
       0.01140169, 0.00968725, 0.12530648, 0.00909905, 0.05864096,
       0.01769644, 0.12110367, 0.07347567, 0.04316046])

In [47]:
def recommand(book_name):
    index = np.where(pt.index == book_name)[0][0]
    similer_item = sorted(list(enumerate(similarity_score[index])),key=lambda x:x[1],reverse=True)[1:6]

    data = []
    for i in similer_item:
        # print(pt.index[i[0]])
        item = []
        temp_df = books[books["Book-Title"]==pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates("Book-Title")["Book-Title"].values))
        item.extend(list(temp_df.drop_duplicates("Book-Title")["Book-Author"].values))
        item.extend(list(temp_df.drop_duplicates("Book-Title")["Image-URL-M"].values))


        data.append(item)
    return data
        

print(recommand("Zoya"))

[['Fine Things', 'Danielle Steel', 'http://images.amazon.com/images/P/0440200563.01.MZZZZZZZ.jpg'], ['Secrets', 'DANIELLE STEEL', 'http://images.amazon.com/images/P/0440176484.01.MZZZZZZZ.jpg'], ['Kaleidoscope', 'June Stepansky', 'http://images.amazon.com/images/P/0884092097.01.MZZZZZZZ.jpg'], ['Exclusive', 'Sandra Brown', 'http://images.amazon.com/images/P/0446604232.01.MZZZZZZZ.jpg'], ['Five Days in Paris', 'DANIELLE STEEL', 'http://images.amazon.com/images/P/0440222842.01.MZZZZZZZ.jpg']]

In [44]:
import pickle
pickle.dump(populer_50,open("populer.pkl","wb"))

In [48]:
pickle.dump(pt,open("pt.pkl","wb"))
pickle.dump(similarity_score,open("similarity_score.pkl","wb"))
pickle.dump(books,open("books.pkl","wb"))